### ISSUE TITLE
Support helthe/Turbolinks 2.0

### ISSUE THREAD

**Issue by UFOMelkor** [helthe/TurbolinksBundle#11]
Would be nice if this bundle would support helthe/turbolinks 2.0
I had a short view and it looks like changing the composer constraint would be enough (but it was just a quick view).
I can do a PR when my current project calms down a bit (and no one has done before).

**Comment by carlalexander** [comment]
Good call, will take care of this shortly.

**Comment by carlalexander** [comment]
Finally did this sorry!
